-- FIX DATABASE: Delete and Re-upload Problematic Records
-- Generated: 2026-02-06
-- Issue: 250 records with NULL or ZERO values causing ~3,433 Ton actual and ~4,936 Ton target to be missing

-- ========================================
-- STEP 1: DELETE PROBLEMATIC RECORDS
-- ========================================

-- These are the record IDs with NULL or ZERO production values
-- Total: 250 records across all years

DELETE FROM production_annual
WHERE real_ton IS NULL 
   OR potensi_ton IS NULL
   OR real_ton = 0
   OR potensi_ton = 0
   OR real_ton < 0.01
   OR potensi_ton < 0.01;

-- Expected result: 250 rows deleted

-- ========================================
-- STEP 2: VERIFY DELETION
-- ========================================

-- Check remaining records
SELECT 
    year,
    COUNT(*) as records,
    SUM(real_ton) as total_actual,
    SUM(potensi_ton) as total_potential
FROM production_annual
GROUP BY year
ORDER BY year;

-- Expected after deletion (approximately):
-- 2023: ~531 records, ~140,396 Ton actual, ~186,158 Ton target
-- 2024: ~555 records, ~135,503 Ton actual, ~188,827 Ton target
-- 2025:  ~552 records, ~142,234 Ton actual, ~189,792 Ton target

-- ========================================
-- STEP 3: RE-INSERT CORRECT DATA
-- ========================================

-- NOTE: The 250 deleted records need to be re-inserted with CORRECT values from Excel
-- This requires:
--   1. Load source Excel file (data_gabungan.xlsx or Realisasi vs Potensi PT SR.xlsx)
--   2. Extract the 250 block/year combinations that were deleted
--   3. Get their correct real_ton and potensi_ton values
--   4. Generate INSERT statements

-- The INSERT statements will be generated by a Python script that:
--   a) Reads the Excel source
--   b) Matches block_id + year combinations
--   c) Generates SQL INSERT statements with correct values

-- ========================================
-- TARGET TOTALS (from Boss's Excel)
-- ========================================

-- After fix, totals should be:
-- 2023: Actual = 141,630.61 Ton | Target = 187,781.70 Ton
-- 2024: Actual = 136,553.30 Ton | Target = 190,482.30 Ton  
-- 2025: Actual = 143,382.80 Ton | Target = 191,449.80 Ton
-- TOTAL: Actual = 421,566.71 Ton | Target = 569,713.80 Ton

-- ========================================
-- ROLLBACK PLAN
-- ========================================

-- Before running this, backup the table:
-- CREATE TABLE production_annual_backup AS SELECT * FROM production_annual;

-- If something goes wrong, restore:
-- DELETE FROM production_annual;
-- INSERT INTO production_annual SELECT * FROM production_annual_backup;

-- ========================================
-- EXECUTION NOTES
-- ========================================

-- 1. BACKUP first (recommended)
-- 2. Run DELETE statement
-- 3. Verify deletion with SELECT query
-- 4. Wait for re-insert script to be generated
-- 5. Run INSERT statements
-- 6. Verify final totals match Boss's Excel

/*
STATUS: READY FOR DELETION
DANGER LEVEL: MEDIUM (can be rolled back if backed up)
NEXT: Run backup, then execute DELETE
*/
